### ISSUE TITLE
Display memory in consistent way

### ISSUE THREAD

**Issue by pkliczewski** [theforeman/foreman_kubevirt#4]
Based on the feedback from the mailing list:

> Can you explain why one VM showed 1024Mi where others showed 1Gi for the memory? It looked like it came straight from the API since the console also showed 1Gi where Foreman normally uses GB.

We need to make sure to always use GB while displaying virtual machine memory.

**Comment by pkliczewski** [comment]
I think we need to align with Foreman UX. It seems like they are using GB so we would need to convert. In terms of frictions I would check how Foreman is dealing with it.

**Comment by masayag** [comment]
We can use https://github.com/ManageIQ/manageiq-providers-kubevirt/blob/master/app/models/manageiq/providers/kubevirt/memory_calculator.rb as the memory converter to the same value on foreman_kubevirt plugin side.

(this file has it spec on that repo)
